# steamvr_manifest.py
# Generates and registers an OpenVR application manifest so SteamVR can
# auto-launch OscGoesPurrr alongside the runtime. Ported from
# VRC-Haptic-Pancake/BridgeApp/vr_manifest.py (GPL3 compatible).

import os
import stat
import sys
from pathlib import Path

from utilities import atomic_write_json


APP_KEY = "com.oscgoespurrr.steamvr"
APP_DISPLAY_NAME = "OscGoesPurrr SteamVR Haptics"
APP_DESCRIPTION = "Bridge OSC parameters to SteamVR tracker haptics."


def _user_data_dir() -> str:
    base = os.environ.get("APPDATA") if sys.platform == "win32" else os.path.expanduser("~/.local/share")
    path = os.path.join(base or os.path.expanduser("~"), "OscGoesPurrr")
    Path(path).mkdir(parents=True, exist_ok=True)
    return path


class SteamVRManifest:
    def __init__(self):
        self.app_key = APP_KEY
        self.app_path = sys.executable

        manifest_file = self.app_key + ".vrmanifest"
        self.manifest_path = os.path.join(_user_data_dir(), manifest_file)

        if sys.platform == "win32":
            self.devlauncher_path = self.manifest_path + ".devlaunch.bat"
        else:
            self.devlauncher_path = self.manifest_path + ".devlaunch.sh"

        self._recent = False
        self._data = None
        self._prepare()

    @property
    def is_app_bundled(self) -> bool:
        return getattr(sys, "frozen", False)

    @property
    def is_recent(self) -> bool:
        return self._recent

    def _prepare(self):
        binary_path_type = "binary_path_windows" if sys.platform == "win32" else "binary_path_linux"
        launch_path = self.app_path if self.is_app_bundled else self.devlauncher_path
        self._data = {
            "applications": [{
                "app_key": self.app_key,
                binary_path_type: launch_path,
                "is_dashboard_overlay": True,
                "launch_type": "binary",
                "strings": {
                    "en_us": {
                        "description": APP_DESCRIPTION,
                        "name": APP_DISPLAY_NAME,
                    },
                },
            }],
            "source": "builtin",
        }

    def _save_devlauncher(self):
        if self.is_app_bundled:
            return
        app_main_script = os.path.abspath(sys.argv[0])
        app_dir = os.path.dirname(app_main_script)

        if sys.platform == "win32":
            with open(self.devlauncher_path, "w", encoding="utf-8") as f:
                f.write(
                    "REM Generated by OscGoesPurrr to let SteamVR launch the unbundled app\n"
                    f"cd /d \"{app_dir}\"\n"
                    f"\"{self.app_path}\" \"{app_main_script}\"\n"
                )
        else:
            with open(self.devlauncher_path, "w", encoding="utf-8") as f:
                f.write(
                    "#!/bin/sh\n"
                    "# Generated by OscGoesPurrr to let SteamVR launch the unbundled app\n"
                    f"cd \"{app_dir}\"\n"
                    f"\"{self.app_path}\" \"{app_main_script}\"\n"
                )
            st = os.stat(self.devlauncher_path)
            os.chmod(self.devlauncher_path, st.st_mode | stat.S_IXUSR)

    def save(self):
        if not self._data:
            raise RuntimeError("Manifest data not prepared")
        atomic_write_json(
            self.manifest_path, self._data,
            ensure_ascii=False, sort_keys=True, indent=4,
        )
        if not self.is_app_bundled:
            self._save_devlauncher()
        self._recent = True

    def remove(self):
        for path in (self.devlauncher_path, self.manifest_path):
            try:
                os.remove(path)
            except FileNotFoundError:
                pass
        self._recent = True
