"""The license and the third-party notices stay in step with what ships.

OscGoesPurrr's own code is MIT, but the exe bundles other people's
software whose licenses require their notices to travel with the binary.
THIRD_PARTY_NOTICES.md carries them (generated by
tools/make_third_party_notices.py), the build bundles it, and Help ->
License shows it. These tests catch the easy drift: a dependency added to
requirements.txt without regenerating the notices, or the build forgetting
to bundle them.
"""

import os
import re

from packaging.requirements import Requirement

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _read(name):
    with open(os.path.join(REPO, name), encoding="utf-8") as fh:
        return fh.read()


def _key(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def test_license_is_mit():
    text = _read("LICENSE")
    assert text.startswith("MIT License")
    assert "Copyright (c) 2026 Blise518B" in text


def test_every_runtime_dependency_has_a_notice():
    notices = _read("THIRD_PARTY_NOTICES.md")
    listed = {_key(m.group(1)) for m in re.finditer(r"^\| ([^|]+?) \| [^|]+ \|", notices, re.M)}
    for line in _read("requirements.txt").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            name = Requirement(line).name
            assert _key(name) in listed, (
                f"{name} is in requirements.txt but not in THIRD_PARTY_NOTICES.md -- "
                f"run tools/make_third_party_notices.py")


def test_notices_cover_the_bundled_engine():
    notices = _read("THIRD_PARTY_NOTICES.md")
    assert "| intiface-engine (Buttplug) |" in notices
    assert "## Source for intiface-engine" in notices


def test_build_bundles_the_license_and_notices():
    bat = _read("tools/build_OGP.bat")
    assert '--add-data "LICENSE;."' in bat
    assert '--add-data "THIRD_PARTY_NOTICES.md;."' in bat


def test_bundle_path_finds_them_in_a_source_run():
    from ui import theme
    for name in ("LICENSE", "THIRD_PARTY_NOTICES.md"):
        assert os.path.isfile(theme.bundle_path(name))
